# Generated by Django 2.2 on 2020-08-29 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='webapp.Choice', verbose_name='ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='webapp.Poll', verbose_name='вопрос')),
            ],
        ),
    ]
